In [208]:
import torch
import numpy as np

This data is taken randomly...don't mind🙏

In [209]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [210]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [211]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [212]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.7172,  0.5371, -0.2132],
        [-0.2876, -0.0805, -1.5948]], requires_grad=True)
tensor([-0.2080, -0.4404], requires_grad=True)


In [213]:
#model
def model(x):
  return x @ w.t() + b

In [214]:
#generate predictions
preds = model(inputs)
preds

tensor([[ -25.7478,  -95.4068],
        [ -31.8561, -135.7657],
        [  -3.0032, -128.7516],
        [ -58.1574,  -92.2444],
        [ -13.0600, -139.6523]], grad_fn=<AddBackward0>)

In [233]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

predictions and targets are far away from each other..🥴

In [216]:
#loss function
def mseloss(t1, t2):
  diff = t1-t2
  loss = torch.sum(diff**2)/len(diff)
  return loss

In [217]:
#compute loss
loss = mseloss(preds, targets)
loss

tensor(57947.1133, grad_fn=<DivBackward0>)

In [218]:
#compute gradients
loss.backward()

In [219]:
#adjust weights and bias to minimize the loss
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [220]:
#check loss again
loss = mseloss(preds, targets)
loss

tensor(57947.1133, grad_fn=<DivBackward0>)

In [221]:
#reset gradients
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [222]:
#generate predictions
preds = model(inputs)

In [223]:
#calculate loss again
loss=mseloss(preds, targets)
loss

tensor(24317.2383, grad_fn=<DivBackward0>)

In [224]:
#compute gradients
loss.backward()

In [225]:
#adjust weights and bias and reset gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [226]:
#calculate predictions
preds = model(inputs)

In [227]:
#calculate loss
loss = mseloss(preds, targets)
loss

tensor(10458.1416, grad_fn=<DivBackward0>)

In [228]:
#train for multiple epochs to fast the training
epochs = 1000
for i in range(epochs):
  preds = model(inputs)
  loss = mseloss(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [229]:
#calculate predictions
preds = model(inputs)

In [230]:
#calculate loss
loss = mseloss(preds, targets)
loss

tensor(10.4464, grad_fn=<DivBackward0>)

In [231]:
#predictions
preds

tensor([[ 57.2113,  70.4835],
        [ 81.5582,  98.6511],
        [120.0935, 137.2686],
        [ 21.4765,  38.2285],
        [100.5218, 114.8334]], grad_fn=<AddBackward0>)

In [232]:
#targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

predictions are quite close to the targets after the training...😎